### ISSUE TITLE
Heap_Size property explanation strangeness

### ISSUE THREAD

**Issue by buzden** [saeaadl/aadlv2.1#18]
The `Heap_Size` property is written to specify the **minimum and maximum** heap size requirements. But it has type of `Size` but not `Size_Range`. Of course minimum and maximum requirements can be equal, but to force all to make them equal by the type of the property seems to be strange. So semantics and type of the property are not consistent.

**Comment by reteprelief** [comment]
We will delete the minimum part. The stack size and others only have a single value.
