### ISSUE TITLE
Allow dynamic on Input_Time and Output_Time

### ISSUE THREAD

**Issue by reteprelief** [saeaadl/aadlv2.1#3]
(Source Denis)
Sometimes we don't know a specific offset range. In this case it would to just specify "dynamic".
Proposal: add "dynamic" as additional literal.

**Comment by reteprelief** [comment]
This was approved at the Jan 2016 meeting.

**Comment by reteprelief** [comment]
Documented. Implemented osate/osate-core#670

**Comment by buzden** [comment]
I think that the text should be slighly extended to make it a little bit clearer. I suppose to add "_(if IO occurs)_" between "_Dynamic indicates that_" and "_time can be anytime ..._".

**Comment by reteprelief** [comment]
Do you mean to say that when dynamic is specified there may be no IO ("if IO occur") or to mean that IO will occur ('when IO occur")?

**Comment by buzden** [comment]
We were originally also considering a situation when IO can occur not every dispatch (so, unfrozen buffers are not cleared every time). So, I mean there may be no IO, i.e. "if IO occur".

**Comment by reteprelief** [comment]
thanks. I updated the document.
